swagger: '2.0'
info:
  version: 1.0.0
  title: DT-CREDENTIALS-BR
  description: Expose all services for Serasa Experian to manager Azure and Office 365 credentials.
  contact:
    name: Experian API team - Digital
    email: suporte-api-digital@br.experian.com
host: sandbox-api.serasaexperian.com.br
basePath: /digital/credentials/v1
tags:
- name: Credentials
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
security:
  - OauthSecurityUser:
      - write
  - OauthSecurityClient:
      - write
paths:
  /credentials:
    post:
      tags:
        - "Credentials"
      summary: Retuns user credential data.
      description: Retuns user credential data. To access this method the client (application) must have "CLI-AUTH-IDENTIFIED" authentication and "CLI-1STPARTY" role
      operationId: getCredentials
      produces:
        - application/json
      security:
        - OauthSecurityUser:
            - write
        - OauthSecurityClient:
            - write
      parameters:
        - in: body
          name: CredentialsRequest
          required: true
          schema:
            $ref: '#/definitions/CredentialsRequest'
      responses:
        '200':
          description: User found
          schema:
            $ref: '#/definitions/CredentialsResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorModel'
        '401':
          description: Authorization Failed
          schema:
            $ref: '#/definitions/ErrorModel'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/ErrorModel'
securityDefinitions:
  BasicSecurityUser:
    type: basic
  OauthSecurityUser:
    type: oauth2
    flow: password
    tokenUrl: 'https://sandbox-api.serasaexperian.com.br/security/iam/v1/user-identities/login'
    scopes:
      read: User read scope
      write: User write scope
  OauthSecurityClient:
    type: oauth2
    flow: application
    tokenUrl: 'https://sandbox-api.serasaexperian.com.br/security/iam/v1/client-identities/login'
    scopes:
      read: Client read scope
      write: Client write scope
definitions:
  CredentialsRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string
  CredentialsResponse:
    type: object
    required:
      - fullName
      - id
      - jobTitle
      - email
      - mobilePhone
    properties:
      fullName:
        type: string
      id:
        type: string
      jobTitle:
        type: string
      email:
        type: string
      mobilePhone:
        type: string
      businessPhones:
        type: array
        items:
          $ref: '#/definitions/businessPhone'
  businessPhone:
    required:
      - number
      - type
    type: object
    properties:
      number:
        type: string
      type:
        type: string
  ErrorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string